
import com.tarea.desinf.gui.DialogoDarAltaCompania;
import com.tarea.desinf.gui.DialogoDarBajaCompania;
import com.tarea.desinf.gui.DialogoModificarCompania;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 34675
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonIrDialogo = new javax.swing.JButton();
        ButtonBorrar = new javax.swing.JButton();
        ButtonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonIrDialogo.setText("Crear");
        ButtonIrDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIrDialogoActionPerformed(evt);
            }
        });

        ButtonBorrar.setText("Borrar");
        ButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBorrarActionPerformed(evt);
            }
        });

        ButtonModificar.setText("Modificar");
        ButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(ButtonIrDialogo)
                .addGap(2, 2, 2)
                .addComponent(ButtonModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonBorrar)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonIrDialogo)
                    .addComponent(ButtonBorrar)
                    .addComponent(ButtonModificar))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIrDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIrDialogoActionPerformed
        //crear un dialogo de insertar compañias
        DialogoDarAltaCompania dialogo=new DialogoDarAltaCompania(this, true);
        dialogo.setVisible(true);


    }//GEN-LAST:event_ButtonIrDialogoActionPerformed

    private void ButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBorrarActionPerformed
        DialogoDarBajaCompania bajaCompania=new DialogoDarBajaCompania(this, true);
        bajaCompania.setVisible(true);

    }//GEN-LAST:event_ButtonBorrarActionPerformed

    private void ButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarActionPerformed
        DialogoModificarCompania modificarCompania= new DialogoModificarCompania(this, true);
        modificarCompania.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonModificarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBorrar;
    private javax.swing.JButton ButtonIrDialogo;
    private javax.swing.JButton ButtonModificar;
    // End of variables declaration//GEN-END:variables
}
