
package com.tarea.desinf.gui;

import com.tarea.deinf.dto.CompaniaAerea;
import com.tarea.desinf.controlador.Controlador;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class DialogoDarBajaCompania extends javax.swing.JDialog {

private List<String> codigos=new ArrayList<>();
private List<CompaniaAerea> lista;
private CompaniaAerea compania;
    public DialogoDarBajaCompania(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (rellenarCodigos()){
        DefaultComboBoxModel model=new DefaultComboBoxModel(codigos.toArray());
        ComboBoxCodigos.setModel(model);
        refrescarNombre();
//        for (CompaniaAerea c:lista){
//            System.out.println("Compañia numero:"+c.getPrefijo());
//        }
        }
    }
    //rellena una lista con los codigos de las compañias para utilizar en el combobox
    private boolean rellenarCodigos(){
        lista=Controlador.getListaCompanias();
        if(!lista.isEmpty()){
            for (CompaniaAerea c:lista){
                codigos.add(c.getCodigo());
            }
            return true;
        }
        return false;
    }
    //recupera la compania seleccionada en el combobox
    
    
    //muestra el nombre de la compañia en el Campo segun codigo seleccionado en combobox
    private void refrescarNombre(){
        compania=Controlador.getCompaniaCodigo(ComboBoxCodigos.getSelectedItem().toString());
        TextFieldNombre.setText(compania.getNombre());  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxCodigos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ButtonAceptar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ComboBoxCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCodigosActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        ButtonAceptar.setText("Borrar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE))
                            .addComponent(TextFieldNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCancelar)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAceptar)
                    .addComponent(ButtonCancelar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxCodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCodigosActionPerformed
        refrescarNombre();
       
    }//GEN-LAST:event_ComboBoxCodigosActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        this.dispose();

    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
      //devuelve un 0 con aceptar y un 2 con cancelar y un -1 al cerrar el dialogo sin eleccion
        int opcion=JOptionPane.showConfirmDialog(this, "Estas seguro de borrar compañia", "BORRAR COMPAÑIA", JOptionPane.OK_CANCEL_OPTION);
        if (opcion==0){
            Controlador.eliminarCompania(compania.getPrefijo());
            Controlador.escribirFicheroCSV();
            Controlador.leerFicherosCSV();
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JComboBox<String> ComboBoxCodigos;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
