
package com.tarea.desinf.gui;

import com.tarea.deinf.dto.CompaniaAerea;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class DialogoModificarCompania extends javax.swing.JDialog {
    private List<CompaniaAerea> lista;
    private List<CompaniaAerea> listaaux=new ArrayList<>();
    private List<String> nombres=new ArrayList<>();
    private CompaniaAerea compania;
    private String nombre;
    public DialogoModificarCompania(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (rellenarNombres()){
            DefaultListModel model=new DefaultListModel();
            Listcompanias.setModel(model);
            for (String l:nombres){
                model.addElement(l);
            }
            Listcompanias.setSelectedIndex(0);
            referescarDialogo();
            
        }
    }
    private boolean rellenarNombres(){
        lista=CompaniaAerea.getListaCompanias();
        if (!lista.isEmpty()){
            for (CompaniaAerea c:lista){
                nombres.add(c.getNombre());
            }
        return true;
        }
        return false;
    }
    //rellena una lista con todas las compañias menos la seleccionada para comprobaciones
    private void rellenarListaAux(){
        //conocer cual es la compañia seleccionada
        for (CompaniaAerea c:lista){
            if(!c.getNombre().equals(this.nombre)){   
            }else listaaux.add(c);
        }
    }
    private CompaniaAerea companiaSeleccionada(String nombre){
        for (CompaniaAerea c:lista){
            if (c.getNombre().equals(nombre)) return c;
        }
        return null;
    }
    private void referescarDialogo(){
        nombre=Listcompanias.getSelectedValue();
        compania=companiaSeleccionada(nombre);
        mostrarDatosActuales(); 
        System.out.println(nombre);
    }
    //metodo para seleccionar iniicialmente el primer elemnto para mostarlo
    
    private void mostrarDatosActuales(){
        TextFieldNombre.setText(compania.getNombre());
        TextFieldDireccion.setText(compania.getDireccion());
        TextFieldMunicipio.setText(compania.getMunicipio());
        TextFieldTlfPasjro.setText(compania.getTlfPasajeros());
        TextFieldTlfArpto.setText(compania.getTlfAeropuertos());
        TextFieldCodigo.setText(compania.getCodigo());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listcompanias = new javax.swing.JList<>();
        ButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        TextFieldDireccion = new javax.swing.JTextField();
        TextFieldMunicipio = new javax.swing.JTextField();
        TextFieldTlfPasjro = new javax.swing.JTextField();
        TextFieldTlfArpto = new javax.swing.JTextField();
        TextFieldCodigo = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(Listcompanias);

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Direccion");

        jLabel3.setText("Municipio");

        jLabel5.setText("TlfPasjro");

        jLabel6.setText("TlfArpto");

        jLabel7.setText("Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCancelar)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(TextFieldDireccion)
                    .addComponent(TextFieldMunicipio)
                    .addComponent(TextFieldTlfPasjro)
                    .addComponent(TextFieldTlfArpto)
                    .addComponent(TextFieldCodigo))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextFieldMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TextFieldTlfPasjro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TextFieldTlfArpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCancelar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCancelarActionPerformed
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JList<String> Listcompanias;
    private javax.swing.JTextField TextFieldCodigo;
    private javax.swing.JTextField TextFieldDireccion;
    private javax.swing.JTextField TextFieldMunicipio;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldTlfArpto;
    private javax.swing.JTextField TextFieldTlfPasjro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
