
package com.tarea.desinf.gui;

import com.tarea.deinf.dto.Aeropuerto;
import com.tarea.deinf.dto.Validador;
import com.tarea.desinf.controlador.Controlador;
import com.tarea.desinf.controlador.CargadiorAeropuertos;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;


public class DialogoDarAltaVuelo extends javax.swing.JDialog {

    private CargadiorAeropuertos controladorVuelos=new CargadiorAeropuertos();
    private List<Aeropuerto> listaAeropuertosSalida;
    private List<Aeropuerto> listaAeropuertosllegada;
    PantallaPrincipal frame;
    public DialogoDarAltaVuelo(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        frame=(PantallaPrincipal)parent;
        controladorVuelos.leerFicheroCSV();//rellena una lista con los nombres de los aeropuertos de destino
        listaAeropuertosSalida=controladorVuelos.getListaAeropuertos();//recupera la lista de las compañias de destino
        listaAeropuertosllegada=controladorVuelos.getListaAeropuertos();
        initComponents();
        DefaultComboBoxModel model=new DefaultComboBoxModel(nombresAeropuertos(listaAeropuertosSalida));//modelo para combobox con nombres de aeropuertos
        DefaultComboBoxModel model1=new DefaultComboBoxModel(nombresAeropuertos(listaAeropuertosllegada));//modelo para combobox con nombres de aeropuertos

        comboBoxArptoOrgn.setModel(model1);//le aplicamos el modelo al combobox 
        comboArptoDesno.setModel(model);//le aplicamos el modelo al combobox 
        spinnerHoraSalida.setEditor(new JSpinner.DateEditor(spinnerHoraSalida, "HH:mm"));//damos formato hh:mm
        spinnerHoraLlegada.setEditor(new JSpinner.DateEditor(spinnerHoraLlegada, "HH:mm"));//damos formato hh:mm
    }
    private String[] nombresAeropuertos(List<Aeropuerto> lista){
        if (!lista.isEmpty()){
            String []nombres=new String[listaAeropuertosSalida.size()];
            for (int i=0;i<listaAeropuertosSalida.size();i++){
                nombres[i]=listaAeropuertosSalida.get(i).getNombre();
            }
            return nombres;
        }
       return null;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoVuelo = new javax.swing.JTextField();
        txtDiasOpera = new javax.swing.JTextField();
        comboBoxArptoOrgn = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCompania = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboArptoDesno = new javax.swing.JComboBox<>();
        spinnerHoraSalida = new javax.swing.JSpinner();
        spinnerHoraLlegada = new javax.swing.JSpinner();
        spinnerPlzas = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo Vuelo");

        jLabel2.setText("Aeropuerto Origen");

        jLabel3.setText("Nº Plazas");

        jLabel4.setText("Hora Salida");

        jLabel5.setText("Hora Llegada");

        jLabel6.setText("Dias Opera");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel7.setText("Nombre Compañia");

        jLabel8.setText("Aeropuerto Destino");

        spinnerHoraSalida.setModel(new javax.swing.SpinnerDateModel());

        spinnerHoraLlegada.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));

        spinnerPlzas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoVuelo)
                            .addComponent(txtDiasOpera)
                            .addComponent(comboBoxArptoOrgn, 0, 212, Short.MAX_VALUE)
                            .addComponent(txtCompania)
                            .addComponent(comboArptoDesno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerHoraSalida)
                            .addComponent(spinnerHoraLlegada)
                            .addComponent(spinnerPlzas))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxArptoOrgn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboArptoDesno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerPlzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinnerHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiasOpera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(jButton2))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String compania=txtCompania.getText();
        String codigoVuelo=txtCodigoVuelo.getText();
        String arptoOrgn=comboBoxArptoOrgn.getSelectedItem().toString();
        String arptoDstno=comboArptoDesno.getSelectedItem().toString();
        Integer plazas=(Integer)spinnerPlzas.getValue();
        Date fechaLlegada=(Date)spinnerHoraLlegada.getValue();
        Date fechaSalida=(Date)spinnerHoraSalida.getValue();
        String diasOpera=txtDiasOpera.getText();
        SimpleDateFormat formato=new SimpleDateFormat("HH:mm");//datos formato a los campos de hora
        String horaSalida=formato.format((Date)spinnerHoraSalida.getValue());//formato string  valor al formato HH:mm
        String horaLlegada=formato.format((Date)spinnerHoraLlegada.getValue());//formato string  valor al formato HH:mm
        LocalTime hLlegada=LocalTime.parse(horaLlegada);//formato local time hh:mm
        LocalTime hSalida=LocalTime.parse(horaSalida);//formato local time hh:mm
        
        
        //comprueba si existe algun campo vacio
        if (compania.isEmpty()||codigoVuelo.isEmpty()||diasOpera.isEmpty()){
            JOptionPane.showMessageDialog(this, "NO SE PERMITEN CAMPOS EN BLANCO");
        //comprueba si las horas son correctas    
        }else if ((hSalida.compareTo(hLlegada))==-1||(hSalida.compareTo(hLlegada)==0)){ 
            JOptionPane.showMessageDialog(this, "HORAS ERRONEAS"); 
        //comprueba si el formato de dias opera es correcto
        }else if(!Validador.formatoDiasOpera(diasOpera, this)){
        // si todo es correcto
        }else{
            //comprueba si la compania exite
            
            if(Controlador.existeCoincidencias(compania, "", "", "", "", "")){
                
             //crear un vuelo y añadirlo a lalista de vuelos
             //DialogoDarAltaCompania altaCompania=new DialogoDarAltaCompania(frame, true);
             //altaCompania.setVisible(true);
            }else{//la compania no existe
                
                //crear un dialogo de crear compañia para crear la compania 
                DialogoDarAltaCompania altaCompania=new DialogoDarAltaCompania(this, true);
                altaCompania.setVisible(true);
                
                    
                 }
        }       
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> comboArptoDesno;
    private javax.swing.JComboBox<String> comboBoxArptoOrgn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.Panel panel1;
    private javax.swing.JSpinner spinnerHoraLlegada;
    private javax.swing.JSpinner spinnerHoraSalida;
    private javax.swing.JSpinner spinnerPlzas;
    private javax.swing.JTextField txtCodigoVuelo;
    private javax.swing.JTextField txtCompania;
    private javax.swing.JTextField txtDiasOpera;
    // End of variables declaration//GEN-END:variables
}
